# Generated by Django 5.0.4 on 2024-11-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_answer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='down_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='up_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
